name       : razergenie
version    : 0.3
release    : 1
source     :
    - https://github.com/z3ntu/RazerGenie/archive/v0.3.tar.gz : 8eebdaaa033d6c43c4ecf7fb98e57dc08422e423245c899750173c966be92e4f
license    : GPL-3.0
component  : system.utils
summary    : Standalone Qt application for configuring your Razer devices under GNU/Linux.
description: |
    Standalone Qt application for configuring your Razer devices under GNU/Linux.
builddeps:
    - extra-cmake-modules
    - pkgconfig(Qt5Core)
    - pkgconfig(gl)
rundeps:
    - razer-drivers
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
