name       : razergenie
version    : 0.7
release    : 5
source     :
    - https://github.com/z3ntu/RazerGenie/releases/download/v0.7/RazerGenie-0.7.tar.xz : adf801028a64feb4dcc2f1c0fdbbc931089718312590884aa2d37e636bd83f9b
license    : GPL-3.0
component  : system.utils
summary    : Standalone Qt application for configuring your Razer devices under GNU/Linux.
description: |
    Standalone Qt application for configuring your Razer devices under GNU/Linux.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(gl)
rundeps    :
    - razer-drivers
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
