name       : razergenie
version    : 0.8.1
release    : 6
source     :
    - https://github.com/z3ntu/RazerGenie/archive/v0.8.1.tar.gz : bb347dd8a8560860ff0afe3b1a46c2927da58be5b763e6883b83a1fdcd0c26d6
license    : GPL-3.0
component  : system.utils
summary    : Standalone Qt application for configuring your Razer devices under GNU/Linux.
description: |
    Standalone Qt application for configuring your Razer devices under GNU/Linux.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(gl)
rundeps    :
    - razer-drivers
setup      : |
    %meson_configure -Denable_experimental=true -Dinclude_matrix_discovery=true
build      : |
    %meson_build
install    : |
    %meson_install
