name       : razergenie
version    : 0.4
release    : 1
source     :
    - https://github.com/z3ntu/RazerGenie/releases/download/v0.4/RazerGenie-0.4.tar.xz : 68f7eadac3a6fb4562149370ca7754f5186c057220973ec85ead7f886701b9a9
license    : GPL-3.0
component  : system.utils
summary    : Standalone Qt application for configuring your Razer devices under GNU/Linux.
description: |
    Standalone Qt application for configuring your Razer devices under GNU/Linux.
builddeps:
    - extra-cmake-modules
    - pkgconfig(Qt5Core)
    - pkgconfig(gl)
rundeps:
    - razer-drivers
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
