name       : razergenie
version    : 0.6
release    : 4
source     :
    - https://github.com/z3ntu/RazerGenie/releases/download/v0.6/RazerGenie-0.6.tar.xz : 851c5ce51ec83b4b14e3afb966c70b8b268a8d9bc31e68b223f81af801ec7f7a
license    : GPL-3.0
component  : system.utils
summary    : Standalone Qt application for configuring your Razer devices under GNU/Linux.
description: |
    Standalone Qt application for configuring your Razer devices under GNU/Linux.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(gl)
rundeps    :
    - razer-drivers
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
