name       : razergenie
version    : 0.9.0
release    : 11
source     :
    - https://github.com/z3ntu/RazerGenie/archive/refs/tags/v0.9.0.tar.gz : 8e1f570a4b810df2c5f60d37780cb4efbe8c9058ec77588ab823de7e6225b365
license    : GPL-3.0-or-later
component  : system.utils
summary    : Standalone Qt application for configuring your Razer devices under GNU/Linux.
description: |
    Standalone Qt application for configuring your Razer devices under GNU/Linux.
builddeps  :
    - pkgconfig(Qt5UiTools)
rundeps    :
    - openrazer-current
setup      : |
    %meson_configure -Denable_experimental=true -Dinclude_matrix_discovery=true
build      : |
    %ninja_build
install    : |
    %ninja_install
