name       : razergenie
version    : 0.5
release    : 3
source     :
    - https://github.com/z3ntu/RazerGenie/releases/download/v0.5/RazerGenie-0.5.tar.xz : 80e2ee67a618d719401a7ac604c8554a63d3cb062e8038881b7743ade607d393
license    : GPL-3.0
component  : system.utils
summary    : Standalone Qt application for configuring your Razer devices under GNU/Linux.
description: |
    Standalone Qt application for configuring your Razer devices under GNU/Linux.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(gl)
rundeps    :
    - razer-drivers
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
